'use client';
import {useEffect,useState} from 'react';
import type {Product} from '@/lib/product-templates';
import ProductView from '@/components/product-view';
import '../product-manager.css';
import './catalog.css';
export default function Catalog(){const [products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[deleting,setDeleting]=useState(''),[preview,setPreview]=useState<Product|null>(null);
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/products',{cache:'no-store'});if(!r.ok)throw new Error();setProducts((await r.json() as {products:Product[]}).products);}catch{setError('Impossible de charger vos produits. Réessayez.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function remove(p:Product){if(!window.confirm(`Supprimer « ${p.name} » ? Sa fiche boutique et sa page seront retirées. Les anciennes commandes seront conservées.`))return;setDeleting(p.id);setError('');try{const r=await fetch('/api/products',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:p.id})});if(!r.ok)throw new Error();setProducts(list=>list.filter(x=>x.id!==p.id));if(preview?.id===p.id)setPreview(null);}catch{setError('La suppression a échoué. Le produit est conservé, réessayez.');}finally{setDeleting('');}}
 const visible=products.filter(p=>(filter==='all'||p.status===filter)&&`${p.name} ${p.country}`.toLowerCase().includes(search.toLowerCase()));
 return <section className="pc"><div className="pc-controls"><label>Rechercher un produit<input type="search" placeholder="Nom ou pays…" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Statut<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Tous les produits</option><option value="published">Publiés</option><option value="draft">Brouillons</option></select></label></div><p className="pc-count">{products.length} produit{products.length>1?'s':''} · {products.filter(p=>p.status==='published').length} publié(s)</p>
 {error&&<div role="alert" className="pc-error">{error}{!products.length&&<button onClick={()=>void load()}>Réessayer</button>}</div>}
 {loading?<p role="status">Chargement des produits…</p>:!error&&visible.length===0?<div className="pc-empty"><h2>{products.length?'Aucun résultat':'Votre catalogue est prêt à accueillir vos produits'}</h2><p>{products.length?'Modifiez la recherche ou le filtre.':'Les produits enregistrés avec l’éditeur apparaîtront ici, avec leur statut et leurs actions.'}</p><a href="/dashboard/products/new">+ Ajouter un produit</a></div>:<div className="pc-grid">{visible.map(p=><article key={p.id} className="pc-card"><div className="pc-image"><img src={p.image} alt={p.name}/><span className={p.status==='published'?'published':''}>{p.status==='published'?'Publié':'Brouillon'}</span></div><div className="pc-content"><small>{p.country} · {p.template}</small><h2>{p.name}</h2><strong>{(p.price_cents/100).toFixed(2)} {p.currency==='MAD'?'DH':'LYD'}</strong><div className="pc-actions">{p.status==='published'?<a href={`/products/${p.id}`} target="_blank" rel="noopener noreferrer">Voir ↗</a>:<button onClick={()=>setPreview(p)}>Aperçu</button>}<a href={`/dashboard/products/${p.id}/edit`}>Modifier</a><button className="pc-delete" disabled={!!deleting} onClick={()=>void remove(p)}>{deleting===p.id?'Suppression…':'Supprimer'}</button></div></div></article>)}</div>}
 {preview&&<section className="pc-preview"><div><h2>Aperçu : {preview.name}</h2><button onClick={()=>setPreview(null)}>Fermer l’aperçu</button></div><ProductView product={preview} preview/></section>}</section>;
}
