'use client';
import {useEffect,useState} from 'react';
import type {Product} from '@/lib/product-templates';
import {stockState,productOptions} from '@/lib/product-stock';
import VariantStockEditor from './variant-stock-editor';
export default function StockEditor({product:p,onSaved}:{product:Product;onSaved:(p:Product)=>void}){
 const [tracked,setTracked]=useState(p.stock_quantity!=null),[quantity,setQuantity]=useState(String(p.stock_quantity??0)),[threshold,setThreshold]=useState(String(p.low_stock_threshold??5)),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{setTracked(p.stock_quantity!=null);setQuantity(String(p.stock_quantity??0));setThreshold(String(p.low_stock_threshold??5));},[p.stock_quantity,p.low_stock_threshold]);
 const state=stockState(p);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch('/api/products/stock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:p.id,quantity:tracked?Number(quantity):null,threshold:Number(threshold),expected:p.stock_quantity??null,expectedThreshold:p.low_stock_threshold??5})});const d=await r.json() as {error?:string;product:Product};if(!r.ok)throw new Error(d.error||'Stock non enregistré.');onSaved(d.product);setMessage('Stock enregistré.');}catch(e){setMessage(e instanceof Error?e.message:'Stock non enregistré. Réessayez.');}finally{setBusy(false);}}
 return <div className="pc-stock"><p className={state.soldOut?'stock-empty':state.low?'stock-low':''}>{state.soldOut?'Rupture de stock':state.tracked?`${state.quantity} unité(s) disponible(s)${state.low?' · Stock faible':''}`:productOptions(p).length?'Stock global non suivi · Voir les options':'Stock non suivi'}</p><details><summary>Gérer le stock</summary><form onSubmit={save}><label className="stock-toggle"><input type="checkbox" checked={tracked} onChange={e=>setTracked(e.target.checked)} disabled={busy}/>Suivre le stock global</label>{tracked&&<label>Quantité globale disponible<input type="number" min="0" max="1000000" step="1" required value={quantity} onChange={e=>setQuantity(e.target.value)} disabled={busy}/></label>}<label>Alerte à partir de<input type="number" min="0" max="1000000" step="1" required value={threshold} onChange={e=>setThreshold(e.target.value)} disabled={busy}/></label><small>La confirmation déduit le stock. L’annulation le restitue. Les nouvelles commandes ne réservent pas de quantité. Sans suivi, les commandes restent ouvertes.</small><button disabled={busy}>{busy?'Enregistrement…':'Enregistrer le stock'}</button><p role="status">{message}</p></form><section className="variant-stock-section"><h3>Stock par couleur, taille ou option</h3>{productOptions(p).length?<><p>Indiquez la quantité de chaque option. 0 = rupture de stock. Un champ vide désactive le suivi de cette option. Le seuil d’alerte ci-dessus s’applique aussi aux options. Si le suivi global est activé, les deux stocks limitent les commandes.</p>{productOptions(p).map(option=><VariantStockEditor key={option} product={p} option={option} onSaved={onSaved}/>)}</>:<p>Ajoutez vos couleurs, tailles ou options dans Modifier → Caractéristiques, une par ligne. Exemple : « Noir · M ».</p>}</section></details></div>;
}
