'use client';
import {useState} from 'react';
import {templates,type Product} from '@/lib/product-templates';
import './product-view.css';
export default function ProductView({product:p,preview=false}:{product:Product;preview?:boolean}){
 const t=templates.find(t=>t.id===p.template)||templates[0],ar=p.language==='ar';
 const [quantity,setQuantity]=useState(1),[message,setMessage]=useState(''),[errors,setErrors]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[done,setDone]=useState(false);
 const [orderId]=useState(()=>crypto.randomUUID());
 async function order(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage('');setErrors({});const form=new FormData(e.currentTarget);form.set('productId',p.id);form.set('language',p.language);form.set('orderId',orderId);
 try{const r=await fetch('/api/orders',{method:'POST',body:form,headers:{Accept:'application/json'}});const d=await r.json() as {ok?:boolean;fieldErrors?:Record<string,string>};if(d.ok){setDone(true);setMessage(ar?'توصلنا بطلبك! سنتواصل معك لتأكيد التفاصيل.':'Nous avons reçu votre commande ! Notre équipe vous contactera pour la confirmer.');}else if(d.fieldErrors){setErrors(d.fieldErrors);setMessage(ar?'راجع بيانات الطلب.':'Vérifiez les champs indiqués.');}else throw new Error();}catch{setMessage(ar?'تعذر إرسال الطلب. حاول مجدداً.':'Envoi impossible. Réessayez, vos informations sont conservées.');}finally{setBusy(false);}}
 const labels=ar?['الاسم الكامل','رقم الهاتف','المدينة','العنوان الكامل']:['Nom complet','Téléphone','Ville','Adresse complète'];
 return <div className={`pv ${t.layout}`} dir={ar?'rtl':'ltr'} lang={p.language} style={{'--accent':t.color,'--wash':t.light} as React.CSSProperties}>
 <div className="pv-bar">{ar?'الدفع عند الاستلام · تأكيد الطلب قبل الإرسال':'Paiement à la livraison · Confirmation avant envoi'}</div><header className="pv-header"><a href="/">mustahr<span>®</span></a><a href="#product-order">{ar?'اطلب الآن':'Commander'}</a></header>
 <section className="pv-hero"><div className="pv-photo"><img src={p.image} alt={p.name}/><span>{p.country} · {t.name}</span></div><div className="pv-copy"><small>{t.tag}</small><h1>{p.name}</h1><p>{p.description}</p><strong className="pv-price">{(p.price_cents/100).toFixed(2)} {p.currency==='MAD'?'DH':'LYD'}</strong><p className="pv-delivery">{ar?'التوصيل إلى':'Livraison :'} {p.country} · {ar?'الدفع عند الاستلام':'Paiement à la livraison'}</p><a className="pv-cta" href="#product-order">{ar?'اطلب الآن':'Commander maintenant'} →</a></div></section>
 {p.benefits&&<section className="pv-benefits"><h2>{ar?'اكتشف التفاصيل':'Les détails qui comptent'}</h2><div>{p.benefits.split('\n').filter(Boolean).map((b,i)=><article key={i}><span>{String(i+1).padStart(2,'0')}</span><p>{b}</p></article>)}</div></section>}
 <section className="pv-order" id="product-order"><div><small>{ar?'طلبك بكل سهولة':'VOTRE COMMANDE'}</small><h2>{ar?'خطوة واحدة لطلبك.':'Votre prochain essentiel.'}</h2><p>{ar?'املأ بياناتك. نتواصل معك لتأكيد الطلب قبل الإرسال.':'Remplissez vos coordonnées. Nous vous contactons pour confirmer avant l’envoi.'}</p></div>
 {preview?<div className="pv-preview-note">Aperçu du formulaire de commande : nom, téléphone, ville, adresse et quantité.<br/>Les commandes seront disponibles après publication.</div>:<form onSubmit={order}>{!done&&<><div className="pv-fields">{['name','phone','city','address'].map((name,i)=><label key={name}>{labels[i]}<input name={name} required maxLength={name==='address'?250:100} type={name==='phone'?'tel':'text'} autoComplete={['name','tel','address-level2','street-address'][i]} aria-invalid={!!errors[name]}/>{errors[name]&&<small role="alert">{ar?'تحقق من هذا الحقل':'Vérifiez ce champ'}</small>}</label>)}</div><label>{ar?'الكمية':'Quantité'}<input name="quantity" type="number" min="1" max="99" value={quantity} onChange={e=>setQuantity(Number(e.target.value))} required/></label><p className="pv-total">Total : {(p.price_cents/100*quantity).toFixed(2)} {p.currency==='MAD'?'DH':'LYD'}</p><button className="pv-cta" disabled={busy}>{busy?'…':ar?'تأكيد الطلب':'Confirmer ma commande'}</button></>}<p role="status">{message}</p></form>}</section><footer className="pv-footer"><a href="/">mustahr®</a><a href="/privacy.html">{ar?'سياسة الخصوصية':'Confidentialité'}</a></footer></div>;
}
