'use client';
import {useEffect,useState} from 'react';
type Product={id:string;name:string;status:string;details?:string};
export default function LinkBuilder(){
 const [origin,setOrigin]=useState(''),[products,setProducts]=useState<Product[]>([]),[target,setTarget]=useState('/home.html'),[source,setSource]=useState('facebook'),[medium,setMedium]=useState('paid_social'),[campaign,setCampaign]=useState(''),[content,setContent]=useState(''),[campaignId,setCampaignId]=useState(''),[adsetId,setAdsetId]=useState(''),[adId,setAdId]=useState(''),[message,setMessage]=useState(''),[failed,setFailed]=useState(false);
 useEffect(()=>{setOrigin(location.origin);const controller=new AbortController();fetch('/api/products',{cache:'no-store',signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error();return r.json() as Promise<{products:Product[]}>;}).then(data=>setProducts((data.products||[]).filter((p:Product)=>p.status==='published'))).catch(()=>{if(!controller.signal.aborted)setFailed(true);});return()=>controller.abort();},[]);
 const url=origin?new URL(target,origin):null;
 if(url){Object.entries({utm_source:source,utm_medium:medium,utm_campaign:campaign,utm_content:content,campaign_id:campaignId,adset_id:adsetId,ad_id:adId}).forEach(([k,v])=>{if(v.trim())url.searchParams.set(k,v.trim());});}
 const link=campaign.trim()&&source.trim()&&medium.trim()?url?.toString()||'':'';
 const fields:[string,string,(v:string)=>void,boolean][]=[['Source',source,setSource,true],['Support',medium,setMedium,true],['Nom de campagne',campaign,setCampaign,true],['Nom de publicité (optionnel)',content,setContent,false],['ID campagne (optionnel)',campaignId,setCampaignId,false],['ID ensemble (optionnel)',adsetId,setAdsetId,false],['ID publicité (optionnel)',adId,setAdId,false]];
 function productPath(p:Product){let details:Record<string,string>={};try{details=JSON.parse(p.details||'{}');}catch{}return details.legacy==='true'?(p.id==='car-charger'?'/store.html':'/vegetable-cutter.html'):'/products/'+encodeURIComponent(p.id);}
 return <section className="campaign-builder"><div><span className="campaign-eyebrow">VOTRE PROCHAINE CAMPAGNE</span><h2>Un lien, une origine claire.</h2><p>Créez un lien pour chaque campagne ou publicité, puis utilisez-le comme URL de destination dans votre annonce. Ouvrez ce tableau depuis le domaine que vous utilisez dans vos annonces.</p></div><div className="campaign-fields"><label>Page de destination<select value={target} onChange={e=>{setTarget(e.target.value);setMessage('');}}><option value="/home.html">Accueil de la boutique</option>{products.map(p=><option key={p.id} value={productPath(p)}>{p.name}</option>)}</select></label>{fields.map(([label,value,set,required])=><label key={label}>{label}<input value={value} maxLength={160} required={required} placeholder={label==='Nom de campagne'?'Ex. Chargeur — Octobre':''} onChange={e=>{set(e.target.value);setMessage('');}}/></label>)}</div>{failed&&<p role="alert">Catalogue indisponible. Le lien vers l’accueil reste disponible.</p>}<div className="campaign-link"><label>Lien à utiliser dans votre annonce<textarea readOnly value={link} placeholder="Renseignez la source, le support et le nom de campagne." rows={3}/></label><button disabled={!link} onClick={async()=>{try{await navigator.clipboard.writeText(link);setMessage('Lien copié.');}catch{setMessage('Sélectionnez le lien ci-dessus pour le copier.');}}}>Copier le lien</button></div><p role="status">{message}</p><small>Les identifiants sont facultatifs. Utilisez des noms stables et ne placez aucune information personnelle dans le lien.</small></section>;
}
