import {salesQuery,dayStart,shiftDate} from './sales-statistics';
export type OrderCosts={unit_cost_cents:number;delivery_cost_cents:number;return_cost_cents:number;loss_cents:number;revision:number};
export type ProfitOrder={id:string;created_at:string;name:string;product_name:string;quantity:number;total_cents:number;currency:string;status:string;incident:string;costs:OrderCosts|null};
export type ProfitTotals={currency:string;revenue_cents:number;product_cost_cents:number;delivery_cost_cents:number;return_cost_cents:number;loss_cents:number;ad_spend_cents:number;missing_costs:number;ad_entries:number;orders:number;profit_cents:number};
export type AdSpend={id:string;date:string;currency:string;amount_cents:number;note:string;revision:number};
export type ProfitReport={totals:ProfitTotals[];orders:ProfitOrder[];expenses:AdSpend[];orderTotal:number;expenseTotal:number;page:number;adPage:number;generatedAt:string};
export function moneyInput(value:unknown){if(typeof value!=='string'||!/^\d{1,7}([.,]\d{1,2})?$/.test(value))throw Error('Entrez un montant positif ou nul, avec au maximum deux décimales.');const [whole,fraction='']=value.replace(',','.').split('.');const cents=Number(whole)*100+Number(fraction.padEnd(2,'0'));if(!Number.isSafeInteger(cents)||cents>100000000)throw Error('Montant trop élevé.');return cents;}
export function uuid(value:unknown){if(typeof value!=='string'||!/^[a-f0-9-]{36}$/i.test(value))throw Error('Référence invalide.');return value;}
export function version(value:unknown){if(typeof value!=='number'||!Number.isSafeInteger(value)||value<0)throw Error('Version invalide.');return value;}
export function validateCosts(input:Record<string,unknown>){if(!input||typeof input!=='object')throw Error('Données invalides.');return {id:uuid(input.id),revision:version(input.revision),unit_cost_cents:moneyInput(input.unitCost),delivery_cost_cents:moneyInput(input.deliveryCost),return_cost_cents:moneyInput(input.returnCost),loss_cents:moneyInput(input.loss)};}
export function validateExpense(input:Record<string,unknown>){if(!input||typeof input!=='object')throw Error('Données invalides.');if(typeof input.date!=='string')throw Error('Date invalide.');dayStart(input.date);if(input.date<'2020-01-01'||input.date>'2100-12-31')throw Error('Date invalide.');if(!['MAD','LYD'].includes(String(input.currency)))throw Error('Devise invalide.');if(typeof input.note!=='string'||input.note.length>200)throw Error('Le libellé est limité à 200 caractères.');return {id:uuid(input.id),revision:version(input.revision),date:input.date,currency:input.currency as string,amount_cents:moneyInput(input.amount),note:input.note.trim()};}
export function profitQuery(params:URLSearchParams){salesQuery(params);const from=params.get('from')||'',to=params.get('to')||'',currency=params.get('currency')||'';const orderClauses:string[]=[],adClauses:string[]=[],orderBindings:string[]=[],adBindings:string[]=[];if(from){orderClauses.push('o.created_at>=? AND o.created_at<?');orderBindings.push(dayStart(from),dayStart(shiftDate(to,1)));adClauses.push('date>=? AND date<=?');adBindings.push(from,to);}if(currency){orderClauses.push('o.currency=?');orderBindings.push(currency);adClauses.push('currency=?');adBindings.push(currency);}const where=orderClauses.length?'WHERE '+orderClauses.join(' AND '):'',adWhere=adClauses.length?'WHERE '+adClauses.join(' AND '):'';
 const delivered="o.status='Livré' AND COALESCE(d.incident,'') NOT IN ('Refusé','Retour en cours','Retourné')";
 const join='FROM orders o LEFT JOIN order_costs c ON c.order_id=o.id LEFT JOIN order_deliveries d ON d.order_id=o.id';
 const totalsSql=`SELECT o.currency, COUNT(*) AS orders, SUM(CASE WHEN ${delivered} THEN o.total_cents ELSE 0 END) AS revenue_cents, SUM(CASE WHEN ${delivered} THEN COALESCE(c.unit_cost_cents,0)*o.quantity ELSE 0 END) AS product_cost_cents, SUM(COALESCE(c.delivery_cost_cents,0)) AS delivery_cost_cents, SUM(COALESCE(c.return_cost_cents,0)) AS return_cost_cents, SUM(COALESCE(c.loss_cents,0)) AS loss_cents, SUM(CASE WHEN c.order_id IS NULL AND (o.status IN ('Expédié','Livré') OR COALESCE(d.incident,'')!='') THEN 1 ELSE 0 END) AS missing_costs ${join} ${where} GROUP BY o.currency`;
 const rowsSql=`SELECT o.id,o.created_at,o.name,o.product_name,o.quantity,o.total_cents,o.currency,o.status,COALESCE(d.incident,'') AS incident,c.unit_cost_cents,c.delivery_cost_cents,c.return_cost_cents,c.loss_cents,c.revision ${join} ${where} ORDER BY o.created_at DESC,o.id DESC LIMIT 20 OFFSET ?`;
 return {totalsSql,rowsSql,orderBindings,adBindings,adWhere};
}
export function finishProfitTotals(rows:Partial<ProfitTotals>[],ads:{currency:string;ad_spend_cents:number;ad_entries:number}[],currency:string){return (currency?[currency]:['MAD','LYD']).map(currency=>{const raw=rows.find(r=>r.currency===currency),ad=ads.find(r=>r.currency===currency),row={currency,orders:raw?.orders||0,revenue_cents:raw?.revenue_cents||0,product_cost_cents:raw?.product_cost_cents||0,delivery_cost_cents:raw?.delivery_cost_cents||0,return_cost_cents:raw?.return_cost_cents||0,loss_cents:raw?.loss_cents||0,missing_costs:raw?.missing_costs||0,ad_spend_cents:ad?.ad_spend_cents||0,ad_entries:ad?.ad_entries||0};return {...row,profit_cents:row.revenue_cents-row.product_cost_cents-row.delivery_cost_cents-row.return_cost_cents-row.loss_cents-row.ad_spend_cents};});}
