'use client';
import {useEffect,useRef,useState} from 'react';
import {type ProfitOrder,type OrderCosts} from '@/lib/order-profit';
const values=(costs:OrderCosts|null)=>({unitCost:costs?(costs.unit_cost_cents/100).toFixed(2):'',deliveryCost:costs?(costs.delivery_cost_cents/100).toFixed(2):'',returnCost:costs?(costs.return_cost_cents/100).toFixed(2):'0',loss:costs?(costs.loss_cents/100).toFixed(2):'0'});
export default function CostEditor({order,onSaved,onDirty}:{order:ProfitOrder;onSaved:()=>void;onDirty:(dirty:boolean)=>void}){
 const [base,setBase]=useState(order.costs),[draft,setDraft]=useState(()=>values(order.costs)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[conflict,setConflict]=useState(false);const working=useRef(false),dirty=JSON.stringify(draft)!==JSON.stringify(values(base)),dirtyRef=useRef(dirty);dirtyRef.current=dirty;
 useEffect(()=>{onDirty(dirty||busy);},[dirty,busy,onDirty]);useEffect(()=>{if(!dirtyRef.current&&!working.current){setBase(order.costs);setDraft(values(order.costs));}},[order.costs?.revision]);
 async function save(event:React.FormEvent){event.preventDefault();if(working.current)return;working.current=true;setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/profit/costs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:order.id,...draft,revision:base?.revision||0})});const data=await response.json() as {costs?:OrderCosts;error?:string};if(!response.ok||!data.costs){setConflict(response.status===409);throw Error(data.error||'Enregistrement indisponible.');}setBase(data.costs);setDraft(values(data.costs));setConflict(false);setMessage('Coûts enregistrés');onDirty(false);onSaved();}catch(e){setError(e instanceof Error?e.message:'Envoi interrompu. Réessayez avec les mêmes informations.');}finally{working.current=false;setBusy(false);}}
 async function reload(){if(working.current)return;if(dirty&&!window.confirm('Remplacer vos coûts non enregistrés par la dernière version ?'))return;working.current=true;setBusy(true);setError('');try{const response=await fetch('/api/profit/costs?'+new URLSearchParams({id:order.id}),{cache:'no-store'});const data=await response.json() as {costs:OrderCosts|null;error?:string};if(!response.ok)throw Error(data.error||'Coûts indisponibles.');setBase(data.costs);setDraft(values(data.costs));setConflict(false);setMessage('Dernière version chargée');onDirty(false);onSaved();}catch(e){setError(e instanceof Error?e.message:'Coûts indisponibles.');}finally{working.current=false;setBusy(false);}}
 return <form onSubmit={save} className="profit-cost-form"><fieldset disabled={busy}><legend>Coûts réels · {order.currency==='MAD'?'DH':order.currency}</legend><div className="profit-cost-grid">{(['unitCost','deliveryCost','returnCost','loss'] as const).map((key,index)=><label key={key}>{['Coût produit par unité','Livraison (total commande)','Retour (total commande)','Perte produit non récupérée'][index]}<input type="number" min="0" max="1000000" step="0.01" required value={draft[key]} onChange={e=>{setDraft(s=>({...s,[key]:e.target.value}));setMessage('');}}/></label>)}</div><p>Coût produit déduit pour {order.quantity} unité(s) livrée(s). Les frais et pertes saisis sont déduits même si la commande est annulée. Saisissez 0 pour un coût connu comme nul.</p><button type="submit" disabled={conflict||(!dirty&&!!base)}>{busy?'Enregistrement…':'Enregistrer les coûts'}</button></fieldset><p role="status">{dirty?'Modifications non enregistrées':message}</p>{error&&<p className="profit-error" role="alert">{error}</p>}{(conflict||(order.costs?.revision||0)!==(base?.revision||0))&&<button type="button" disabled={busy} onClick={()=>void reload()}>Recharger la dernière version</button>}</form>;
}
