'use client';
import {useEffect,useState} from 'react';
import {localDate,shiftDate,salesTotals,type SalesReport} from '@/lib/sales-statistics';
const money=(cents:number,currency:string)=>new Intl.NumberFormat('fr-MA',{minimumFractionDigits:2,maximumFractionDigits:2}).format(cents/100)+' '+(currency==='MAD'?'DH':currency);
export default function Statistics(){
 const [period,setPeriod]=useState('all'),[currency,setCurrency]=useState(''),[from,setFrom]=useState(()=>localDate()),[to,setTo]=useState(()=>localDate()),[custom,setCustom]=useState({from:'',to:''}),[reload,setReload]=useState(0),[data,setData]=useState<SalesReport|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const params=new URLSearchParams();if(currency)params.set('currency',currency);if(period==='custom'&&custom.from){params.set('from',custom.from);params.set('to',custom.to);}else if(period!=='all'&&period!=='custom'){const today=localDate();params.set('from',shiftDate(today,-(Number(period)-1)));params.set('to',today);}const query=params.toString();
 useEffect(()=>{let live=true;const controller=new AbortController();let pending=false;setData(null);setError('');setLoading(true);async function load(){if(pending)return;pending=true;try{const response=await fetch('/api/statistics'+(query?'?'+query:''),{cache:'no-store',signal:controller.signal});const result=await response.json() as SalesReport&{error?:string};if(!response.ok)throw new Error(result.error||'Statistiques indisponibles.');if(live){setData(result);setError('');}}catch(e){if(live&&!controller.signal.aborted)setError(e instanceof Error?e.message:'Statistiques indisponibles.');}finally{pending=false;if(live)setLoading(false);}}void load();const timer=setInterval(()=>{if(!document.hidden)void load();},15000);return()=>{live=false;controller.abort();clearInterval(timer);};},[query,reload]);
 const totals=data?salesTotals(data.products):null;
 function choosePeriod(value:string){if(value==='custom')setCustom({from,to});setPeriod(value);}
 return <><section className="sales-filters"><label>Période<select value={period} onChange={e=>choosePeriod(e.target.value)}><option value="all">Tout l’historique</option><option value="1">Aujourd’hui</option><option value="7">7 derniers jours</option><option value="30">30 derniers jours</option><option value="custom">Dates personnalisées</option></select></label><label>Marché / devise<select value={currency} onChange={e=>setCurrency(e.target.value)}><option value="">Tous · DH et LYD séparés</option><option value="MAD">Maroc · DH</option><option value="LYD">Libye · LYD</option></select></label><button disabled={loading} onClick={()=>setReload(n=>n+1)}>Actualiser</button>{period==='custom'&&<form onSubmit={e=>{e.preventDefault();if(from>to){setError('La date de fin doit suivre la date de début.');return;}setCustom({from,to});}}><label>Du<input type="date" required value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Au<input type="date" required min={from} value={to} onChange={e=>setTo(e.target.value)}/></label><button>Appliquer</button></form>}</section>
 <p className="sales-period-note">Période basée sur la date de création des commandes, heure du Maroc. Statuts actuels. {period==='custom'&&custom.from&&<>Dates appliquées : {custom.from} → {custom.to}.</>}</p>
 {error&&<div className="sales-error" role="alert">{error}{data&&' Les derniers chiffres affichés sont conservés.'}<button onClick={()=>setReload(n=>n+1)}>Réessayer</button></div>}
 {loading&&!data?<p className="sales-loading" role="status">Chargement des statistiques…</p>:data&&totals&&<><section className="sales-summary"><article><span>Commandes reçues</span><strong>{totals.orders}</strong><small>{totals.pending} à confirmer · {totals.cancelled} annulée(s)</small></article><article><span>Commandes confirmées</span><strong>{totals.confirmed}</strong><small>Inclut préparation, expédition et livraison</small></article><article><span>Commandes livrées</span><strong>{totals.delivered}</strong><small>{totals.orders?Math.round(totals.delivered/totals.orders*100):0} % des commandes reçues</small></article>{(currency?[currency]:['MAD','LYD']).map(c=><article className="sales-revenue" key={c}><span>Chiffre d’affaires livré · {c==='MAD'?'Maroc':'Libye'}</span><strong>{money(totals.revenue[c]||0,c)}</strong><small>Commandes au statut « Livré » uniquement</small></article>)}</section>
 <section className="sales-table"><div className="sales-table-heading"><div><h2>Résultats par produit</h2><p>{data.products.length} ligne(s) · Actualisation automatique</p></div><span>Mis à jour : {new Date(data.generatedAt).toLocaleTimeString('fr-MA',{timeZone:'Africa/Casablanca',hour:'2-digit',minute:'2-digit'})}</span></div>{!data.products.length?<div className="sales-empty"><h3>Aucune commande dans cette période</h3><p>Choisissez une autre période ou un autre marché.</p></div>:<div className="sales-table-scroll"><table><thead><tr><th>Produit</th><th>Devise</th><th>Commandes</th><th>Confirmées</th><th>Livrées</th><th>Annulées</th><th>Chiffre d’affaires livré</th></tr></thead><tbody>{data.products.map(p=><tr key={JSON.stringify([p.product_id,p.currency])}><td><strong>{p.product_name}</strong><small>{p.catalog_status&&p.catalog_status!=='archived'?'Produit du catalogue':'Produit retiré · historique conservé'}</small></td><td>{p.currency==='MAD'?'DH':p.currency}</td><td>{p.orders}<small>{p.pending} à confirmer</small></td><td>{p.confirmed}</td><td>{p.delivered}<small>{p.delivered_units} unité(s)</small></td><td>{p.cancelled}</td><td><strong>{money(p.revenue_cents,p.currency)}</strong></td></tr>)}</tbody></table></div>}</section>
 <div className="sales-explanation"><strong>Comment lire ces chiffres</strong><p>Les commandes confirmées comprennent les statuts Confirmé, En préparation, Expédié et Livré. Le chiffre d’affaires livré utilise les totaux enregistrés au moment de chaque commande, après remise et avec les frais de livraison. Il ne représente pas le bénéfice ni une confirmation d’encaissement. Les commandes supprimées définitivement ne sont plus comptabilisées.</p></div></>}
 </>;
}
