'use client';
import {offerMode} from '@/lib/product-pricing';
type Row={quantity:string;total:string};
export default function BundleEditor({id,price,currency,details,onChange}:{id:string;price:string;currency:string;details:Record<string,string>;onChange:(details:Record<string,string>)=>void}){
 const mode=offerMode({id,price_cents:Math.round(Number(price)*100),details:JSON.stringify(details)});
 let rows:Row[]=[];try{rows=JSON.parse(details.bundleOffers||'[]');if(!Array.isArray(rows))rows=[];}catch{}
 function setRows(next:Row[]){onChange({...details,bundleOffers:JSON.stringify(next)});}
 return <fieldset className="pm-detail-group pm-bundles"><legend>Offres par quantité</legend><label>Type d’offre<select value={mode} onChange={e=>onChange({...details,offerMode:e.target.value})}><option value="none">Prix normal · aucune remise</option>{id==='car-charger'&&<option value="charger">10 % sur les unités supplémentaires</option>}<option value="bundles">Lots à prix réduit</option></select></label>{mode==='bundles'&&<><p>Le prix du lot couvre les produits uniquement. La livraison est ajoutée une fois par commande. Chaque offre s’applique à sa quantité exacte et remplace toute autre remise.</p>{rows.map((row,i)=><div className="pm-bundle-row" key={i}><label>Quantité<input type="number" min="2" max={id==='vegetable-cutter'?11:99} step="1" required value={row.quantity} onChange={e=>setRows(rows.map((r,n)=>n===i?{...r,quantity:e.target.value}:r))}/></label><label>Prix total du lot ({currency})<input type="number" min={Number(price)||1} step=".01" required value={row.total} onChange={e=>setRows(rows.map((r,n)=>n===i?{...r,total:e.target.value}:r))}/></label><button type="button" className="pm-secondary" onClick={()=>setRows(rows.filter((_,n)=>n!==i))}>Retirer</button></div>)}<button type="button" className="pm-secondary" disabled={rows.length>=6} onClick={()=>setRows([...rows,{quantity:'',total:''}])}>+ Ajouter une offre</button><small>Maximum 6 lots. Choisissez des quantités différentes et un prix inférieur au total sans remise.</small></>}{mode==='charger'&&<p>Une unité au prix normal, puis 10 % de remise sur chaque unité supplémentaire.</p>}</fieldset>;
}
