'use client';
import {useEffect,useRef,useState} from 'react';
import {type CustomerOrder} from '@/lib/customer-history';
import {contactOutcomes,emptyConfirmation,confirmationMessage,confirmationLink,type Confirmation} from '@/lib/order-confirmation';
export default function ConfirmationTools({order,onSaved,onDirty,onBusy,locked}:{order:CustomerOrder;onSaved:(confirmation:Confirmation)=>void;onDirty:(dirty:boolean)=>void;onBusy:(busy:boolean)=>void;locked:boolean}){
 const initial=order.confirmation||emptyConfirmation;
 const [base,setBase]=useState(initial),[notes,setNotes]=useState(initial.notes),[outcome,setOutcome]=useState(initial.outcome),[date,setDate]=useState(initial.follow_up_date),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(''),[conflict,setConflict]=useState(false),[language,setLanguage]=useState<'fr'|'ar'>(order.language==='ar'?'ar':'fr'),[message,setMessage]=useState(()=>confirmationMessage(order,order.language==='ar'?'ar':'fr'));
 const dirty=notes!==base.notes||outcome!==base.outcome||date!==base.follow_up_date,working=useRef(false),dirtyRef=useRef(dirty);dirtyRef.current=dirty;
 useEffect(()=>{onDirty(dirty);},[dirty,onDirty]);
 useEffect(()=>{const next=order.confirmation||emptyConfirmation;if(!dirtyRef.current&&!working.current){setBase(next);setNotes(next.notes);setOutcome(next.outcome);setDate(next.follow_up_date);}},[order.confirmation?.revision]);
 async function save(event:React.FormEvent){event.preventDefault();if(working.current||locked)return;working.current=true;onBusy(true);setBusy(true);setError('');setSaved('');
 try{const response=await fetch('/api/orders/confirmation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:order.id,notes,outcome,follow_up_date:date,revision:base.revision})});const data=await response.json() as {confirmation?:Confirmation;error?:string};if(!response.ok||!data.confirmation){setConflict(response.status===409);throw Error(data.error||'Enregistrement indisponible. Réessayez.');}const next=data.confirmation;setBase(next);setNotes(next.notes);setOutcome(next.outcome);setDate(next.follow_up_date);setConflict(false);setSaved('Suivi enregistré');onSaved(next);onDirty(false);}catch(e){setError(e instanceof Error?e.message:'Envoi interrompu. Vos modifications sont conservées ; réessayez.');}finally{working.current=false;setBusy(false);onBusy(false);}}
 async function reload(){if(dirty&&!window.confirm('Remplacer vos modifications non enregistrées par la dernière version du suivi ?'))return;if(working.current||locked)return;working.current=true;onBusy(true);setBusy(true);setError('');try{const response=await fetch('/api/orders/confirmation?'+new URLSearchParams({id:order.id}),{cache:'no-store'});const data=await response.json() as {confirmation?:Confirmation;error?:string};if(!response.ok||!data.confirmation)throw Error(data.error||'Suivi indisponible.');setBase(data.confirmation);setNotes(data.confirmation.notes);setOutcome(data.confirmation.outcome);setDate(data.confirmation.follow_up_date);onSaved(data.confirmation);onDirty(false);setConflict(false);setSaved('Dernière version chargée');}catch(e){setError(e instanceof Error?e.message:'Suivi indisponible.');}finally{working.current=false;setBusy(false);onBusy(false);}}
 const link=confirmationLink(order.phone,order.currency,message),changedElsewhere=(order.confirmation?.revision||0)!==base.revision;
 return <section className="confirmation-tools" aria-label="Confirmation et suivi"><h3>Confirmation et suivi</h3><div className="confirmation-grid"><form onSubmit={save} className="confirmation-form"><fieldset disabled={busy||locked}><legend>Après votre appel</legend><label>Résultat du contact<select value={outcome} onChange={e=>{setOutcome(e.target.value);setSaved('');}}>{contactOutcomes.map(value=><option key={value} value={value}>{value||'Pas encore contacté'}</option>)}</select></label><label>Date de relance<input type="date" min="2020-01-01" max="2100-12-31" value={date} onChange={e=>{setDate(e.target.value);setSaved('');}}/><small>Date du Maroc. Effacez ce champ une fois la relance terminée.</small></label><label>Notes d’appel<textarea maxLength={2000} rows={4} value={notes} onChange={e=>{setNotes(e.target.value);setSaved('');}} placeholder="Disponibilité du client, précision d’adresse, résultat de l’appel…"/><small>{notes.length}/2 000 caractères</small></label><button type="submit" className="confirmation-save" disabled={!dirty||conflict}>{busy?'Enregistrement…':'Enregistrer le suivi'}</button></fieldset><p role="status" className="confirmation-feedback">{dirty?'Modifications non enregistrées':saved}</p>{error&&<p className="history-error" role="alert">{error}</p>}{(conflict||changedElsewhere)&&<div className="confirmation-conflict"><p>Une autre version du suivi est disponible.</p><button type="button" disabled={busy} onClick={()=>void reload()}>Recharger la dernière version</button></div>}</form><div className="confirmation-message"><h4>Message de confirmation</h4><label>Langue<select value={language} onChange={e=>{const value=e.target.value as 'fr'|'ar';setLanguage(value);setMessage(confirmationMessage(order,value));}}><option value="fr">Français</option><option value="ar">العربية</option></select></label><label>Relisez et modifiez le message<textarea rows={9} maxLength={4000} dir={language==='ar'?'rtl':'ltr'} value={message} onChange={e=>setMessage(e.target.value)}/></label><div className="confirmation-message-actions"><button type="button" onClick={()=>setMessage(confirmationMessage(order,language))}>Réinitialiser le message</button>{link?<a href={link} target="_blank" rel="noopener noreferrer" className="confirmation-whatsapp">Ouvrir WhatsApp</a>:<span className="history-error">{message.trim()?'Numéro non reconnu au format international.':'Ajoutez un message pour ouvrir WhatsApp.'}</span>}</div><p>WhatsApp s’ouvre avec ce texte. Vous choisissez quand l’envoyer. L’envoi ne modifie pas le statut de la commande.</p></div></div></section>;
}
