'use client';
import {useEffect,useState} from 'react';
import {customerKey,type CustomerOrder} from '@/lib/customer-history';
export type HistoryResponse={anchor?:CustomerOrder;orders:CustomerOrder[];total:number;delivered:number;cancelled:number;duplicates:{id:string;status:string}[];page:number;hasMore:boolean};
export default function CustomerHistory({orderId,phone,currency='MAD',revision=0}:{orderId?:string;phone?:string;currency?:string;revision?:number}){
 const [data,setData]=useState<HistoryResponse|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[page,setPage]=useState(0),[retry,setRetry]=useState(0);
 const key=phone?customerKey(phone,currency):null;
 useEffect(()=>{setPage(0);},[orderId,key,currency]);
 useEffect(()=>{setData(null);setError('');if(!orderId&&!key){setLoading(false);return;}const controller=new AbortController();setLoading(true);
 const timer=setTimeout(()=>{const params=new URLSearchParams({page:String(page)});if(orderId)params.set('orderId',orderId);else{params.set('phone',phone!);params.set('currency',currency);}fetch('/api/orders/customer?'+params,{cache:'no-store',signal:controller.signal}).then(async response=>{const body=await response.json() as HistoryResponse & {error?:string};if(!response.ok)throw Error(body.error||'Historique indisponible.');return body as HistoryResponse;}).then(value=>{if(!controller.signal.aborted)setData(value);}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Historique indisponible.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},orderId?0:500);
 return()=>{clearTimeout(timer);controller.abort();};},[orderId,key,currency,page,retry,revision]);
 if(!orderId&&!key)return null;
 return <section className="customer-history" aria-label="Historique du client"><header><h3>{orderId?'Autres commandes de ce numéro':'Historique de ce numéro'}</h3><button type="button" className="history-refresh" onClick={()=>setRetry(n=>n+1)} disabled={loading}>Actualiser</button></header>{loading&&<p role="status">Recherche de l’historique…</p>}{error&&<p className="history-error" role="alert">{error} <button type="button" onClick={()=>setRetry(n=>n+1)}>Réessayer</button></p>}{data&&<><div className="history-stats"><span><strong>{data.total}</strong> commande(s)</span><span><strong>{data.delivered}</strong> livrée(s)</span><span><strong>{data.cancelled}</strong> annulée(s)</span></div><p className="history-note">Même numéro de téléphone ; vérifiez le nom et l’adresse avant de conclure qu’il s’agit du même client.</p>{data.duplicates.length>0&&<p className="duplicate-warning" role="status">Doublon possible avec {data.duplicates.map(d=>'#'+d.id.slice(0,8)).join(', ')}. Vérifiez avant d’expédier.</p>}{!data.total?<p>Aucune autre commande pour ce numéro.</p>:<div className="history-list">{data.orders.map(order=><article key={order.id} className="history-item"><div><strong>#{order.id.slice(0,8)} · {order.name}</strong><time dateTime={order.created_at}>{new Date(order.created_at).toLocaleString('fr-MA',{timeZone:'Africa/Casablanca',dateStyle:'medium',timeStyle:'short'})}</time></div><span className="history-status">{order.status}</span><p>{order.product_name} · {order.quantity} unité(s) · {(order.total_cents/100).toFixed(2)} {order.currency==='MAD'?'DH':order.currency}</p><p dir="auto">{order.city} · {order.address}</p></article>)}</div>}{(page>0||data.hasMore)&&<nav className="history-pagination" aria-label="Pages de l’historique"><button type="button" disabled={page===0} onClick={()=>setPage(n=>n-1)}>Précédent</button><span>Page {page+1}</span><button type="button" disabled={!data.hasMore} onClick={()=>setPage(n=>n+1)}>Suivant</button></nav>}</>}</section>;
}
