'use client';
import {useEffect,useRef,useState} from 'react';
import {type CustomerOrder} from '@/lib/customer-history';
import {deliveryIncidents,emptyDelivery,safeTrackingUrl,type Delivery} from '@/lib/order-delivery';
export default function DeliveryTools({order,onSaved,onDirty,onBusy,locked}:{order:CustomerOrder;onSaved:(delivery:Delivery)=>void;onDirty:(dirty:boolean)=>void;onBusy:(busy:boolean)=>void;locked:boolean}){
 const initial=order.delivery||emptyDelivery;
 const [base,setBase]=useState(initial),[draft,setDraft]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[conflict,setConflict]=useState(false);
 const dirty=JSON.stringify(draft)!==JSON.stringify(base),working=useRef(false),dirtyRef=useRef(dirty);dirtyRef.current=dirty;
 useEffect(()=>{onDirty(dirty);},[dirty,onDirty]);
 useEffect(()=>{if(!dirtyRef.current&&!working.current){const next=order.delivery||emptyDelivery;setBase(next);setDraft(next);}},[order.delivery?.revision]);
 function change(key: keyof Delivery,value:string){setDraft(s=>({...s,[key]:value}));setMessage('');}
 async function save(event:React.FormEvent){event.preventDefault();if(working.current||locked)return;working.current=true;setBusy(true);onBusy(true);setError('');setMessage('');
 try{const response=await fetch('/api/orders/delivery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:order.id,...draft,revision:base.revision})});const data=await response.json() as {delivery?:Delivery;error?:string};if(!response.ok||!data.delivery){setConflict(response.status===409);throw Error(data.error||'Enregistrement indisponible. Réessayez.');}setBase(data.delivery);setDraft(data.delivery);onSaved(data.delivery);onDirty(false);setConflict(false);setMessage('Suivi livraison enregistré');}catch(e){setError(e instanceof Error?e.message:'Envoi interrompu. Vos modifications sont conservées ; réessayez.');}finally{working.current=false;setBusy(false);onBusy(false);}}
 async function reload(){if(working.current||locked)return;if(dirty&&!window.confirm('Remplacer vos modifications non enregistrées par la dernière version du suivi livraison ?'))return;working.current=true;setBusy(true);onBusy(true);setError('');try{const response=await fetch('/api/orders/delivery?'+new URLSearchParams({id:order.id}),{cache:'no-store'});const data=await response.json() as {delivery?:Delivery;error?:string};if(!response.ok||!data.delivery)throw Error(data.error||'Suivi indisponible.');setBase(data.delivery);setDraft(data.delivery);onSaved(data.delivery);onDirty(false);setConflict(false);setMessage('Dernière version chargée');}catch(e){setError(e instanceof Error?e.message:'Suivi indisponible.');}finally{working.current=false;setBusy(false);onBusy(false);}}
 const link=safeTrackingUrl(base.tracking_url),changedElsewhere=(order.delivery?.revision||0)!==base.revision;
 return <section className="confirmation-tools delivery-tools" aria-label="Suivi de livraison"><h3>Suivi de livraison</h3><form className="confirmation-form" onSubmit={save}><fieldset disabled={busy||locked}><legend>Transporteur et colis</legend><div className="delivery-fields"><label>Transporteur<input maxLength={100} value={draft.courier} onChange={e=>change('courier',e.target.value)} placeholder="Nom du transporteur"/></label><label>Numéro de suivi<input maxLength={120} dir="ltr" value={draft.tracking_number} onChange={e=>change('tracking_number',e.target.value)} placeholder="Référence du colis"/></label><label className="delivery-wide">Lien de suivi (optionnel)<input type="url" maxLength={500} dir="ltr" value={draft.tracking_url} onChange={e=>change('tracking_url',e.target.value)} placeholder="https://…"/></label><label>Incident de livraison<select value={draft.incident} onChange={e=>change('incident',e.target.value)}>{deliveryIncidents.map(value=><option key={value} value={value}>{value||'Aucun incident'}</option>)}</select></label><label className="delivery-wide">Motif / précisions{draft.incident?' (obligatoire)':''}<textarea maxLength={1000} required={!!draft.incident} rows={3} value={draft.reason} onChange={e=>change('reason',e.target.value)} placeholder="Refus du client, adresse introuvable, colis retourné…"/><small>{draft.reason.length}/1 000 caractères</small></label></div><button type="submit" className="confirmation-save" disabled={!dirty||conflict}>{busy?'Enregistrement…':'Enregistrer la livraison'}</button></fieldset><p role="status" className="confirmation-feedback">{dirty?'Modifications non enregistrées':message}</p>{error&&<p className="history-error" role="alert">{error}</p>}{(conflict||changedElsewhere)&&<div className="confirmation-conflict"><p>Une autre version du suivi est disponible.</p><button type="button" disabled={busy} onClick={()=>void reload()}>Recharger la dernière version</button></div>}</form>{link&&<a className="delivery-track-link" href={link} target="_blank" rel="noopener noreferrer">Ouvrir le suivi du colis</a>}<p className="delivery-note">Renseignez le suivi après chaque retour du transporteur. Mettez à jour le statut de la commande dans « Gestion ». Un incident ne remet pas automatiquement les articles en stock ; vérifiez le colis avant d’ajuster les quantités dans « Mes produits ».</p></section>;
}
