'use client';
import {useEffect,useState} from 'react';
import {templates,type Product} from '@/lib/product-templates';
import ProductView from '@/components/product-view';
import './product-manager.css';
const initial={name:'',description:'',benefits:'',image:'',price:'',country:'Maroc',language:'fr'};
export default function ProductManager(){const [products,setProducts]=useState<Product[]>([]),[open,setOpen]=useState(false),[template,setTemplate]=useState(''),[fields,setFields]=useState(initial),[id,setId]=useState(''),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function refresh(){try{const r=await fetch('/api/products',{cache:'no-store'});if(!r.ok)throw new Error();setProducts((await r.json() as {products:Product[]}).products);}catch{setMessage('Impossible de charger le catalogue. Réessayez.');}}
 useEffect(()=>{void refresh();},[]);
 function start(){setOpen(true);setTemplate('');setFields(initial);setId('');setPreview(false);setMessage('');}
 function edit(p:Product){setOpen(true);setTemplate(p.template);setFields({name:p.name,description:p.description,benefits:p.benefits,image:p.image,price:String(p.price_cents/100),country:p.country,language:p.language});setId(p.id);setPreview(false);setMessage('');}
 const example:Product={id:id||'preview',...fields,price_cents:Math.round(Number(fields.price||0)*100),template,currency:fields.country==='Libye'?'LYD':'MAD',status:'draft',created_at:''};
 async function save(status:string){setBusy(true);setMessage('');try{const r=await fetch('/api/products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,template,id:id||undefined,status})});const d=await r.json() as {error?:string;id:string};if(!r.ok)throw new Error(d.error||'Enregistrement impossible.');setId(d.id);setMessage(status==='published'?'Produit publié : sa page et sa fiche boutique sont disponibles.':'Brouillon enregistré.');await refresh();}catch(e){setMessage(e instanceof Error?e.message:'Réessayez.');}finally{setBusy(false);}}
 return <section className="pm"><div className="pm-heading"><div><small>VOTRE CATALOGUE</small><h2>Produits & modèles</h2><p>Choisissez un modèle, ajoutez votre produit, puis publiez sa page.</p></div><button onClick={start}>+ Ajouter un produit</button></div>
 {message&&<p role="status" className="pm-message">{message}</p>}
 {open&&<div className="pm-editor"><div className="pm-heading"><h3>{template?'2 · Les détails du produit':'1 · Choisissez votre modèle'}</h3><button className="pm-secondary" onClick={()=>setOpen(false)}>Fermer</button></div>
 {!template?<div className="pm-templates">{templates.map(t=><button key={t.id} onClick={()=>setTemplate(t.id)} style={{'--accent':t.color,'--wash':t.light} as React.CSSProperties}><div className={`pm-thumb ${t.layout}`}><span>{t.icon}</span><i/><i/><b/></div><strong>{t.name}</strong><small>{t.layout==='centered'?'Vitrine centrée':t.layout==='editorial'?'Grande image éditoriale':'Image & détails côte à côte'} · Choisir →</small></button>)}</div>:<><button className="pm-secondary" onClick={()=>{setTemplate('');setPreview(false);}}>← Changer de modèle</button><form onSubmit={e=>{e.preventDefault();void save('published');}}><div className="pm-fields"><label>Nom du produit<input required maxLength={120} value={fields.name} onChange={e=>setFields({...fields,name:e.target.value})}/></label><label>Prix ({fields.country==='Libye'?'LYD':'DH'})<input required type="number" min="1" max="1000000" step=".01" value={fields.price} onChange={e=>setFields({...fields,price:e.target.value})}/></label><label>Pays de livraison<select value={fields.country} onChange={e=>setFields({...fields,country:e.target.value})}><option>Maroc</option><option>Libye</option></select></label><label>Langue de la page<select value={fields.language} onChange={e=>setFields({...fields,language:e.target.value})}><option value="fr">Français</option><option value="ar">العربية</option></select></label><label className="pm-wide">Image du produit · URL HTTPS<input required type="url" placeholder="https://…" value={fields.image} onChange={e=>setFields({...fields,image:e.target.value})}/><small>Utilisez le lien direct d’une image de votre produit.</small></label><label className="pm-wide">Description<textarea required maxLength={2000} value={fields.description} onChange={e=>setFields({...fields,description:e.target.value})}/></label><label className="pm-wide">Points forts · un par ligne<textarea maxLength={2000} value={fields.benefits} onChange={e=>setFields({...fields,benefits:e.target.value})}/><small>Ajoutez uniquement les caractéristiques réelles du produit.</small></label></div><div className="pm-actions"><button type="button" className="pm-secondary" onClick={()=>setPreview(!preview)}>{preview?'Masquer':'Voir'} l’aperçu</button><button type="button" className="pm-secondary" disabled={busy} onClick={()=>void save('draft')}>Enregistrer le brouillon</button><button disabled={busy}>{busy?'Enregistrement…':'Publier le produit'}</button></div></form>{preview&&<div className="pm-preview"><ProductView product={example} preview/></div>}</> }</div>}
 <div className="pm-list">{products.map(p=><article key={p.id}><img src={p.image} alt=""/><div><strong>{p.name}</strong><p>{(p.price_cents/100).toFixed(2)} {p.currency==='MAD'?'DH':'LYD'} · {p.status==='published'?'Publié':'Brouillon'}</p></div><button className="pm-secondary" onClick={()=>edit(p)}>Modifier</button>{p.status==='published'&&<a href={`/products/${p.id}`} target="_blank" rel="noopener noreferrer">Voir la page ↗</a>}</article>)}</div><button className="pm-secondary" onClick={()=>void refresh()}>Actualiser le catalogue</button></section>;
}
